menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Grace Keene-Lee', title: 'PhD Student', department: 'Psychology', institution: 'University of Wisconsin, Madison', email: 'gekeene@wisc.edu',image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}


contacts:
- {name: 'Grace Keene-Lee', title: 'PhD Student', department: 'Psychology', institution: 'University of Wisconsin, Madison', email: 'gekeene@wisc.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
