menu:
- {name: 'publications', url: '/publications'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Grace Keene-Lee', title: 'PhD Student', department: 'Psychology', institution: 'University of Wisconsin, Madison', email: 'gekeene@wisc.edu',image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}


research:
- {name: 'Thinking about belief control', url: 'belief-control'}
- {name: 'Moralization of belief & Norms of assertion', url: 'private-belief'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}


contacts:
- {name: 'Grace Keene-Lee', title: 'PhD Student', department: 'Psychology', institution: 'University of Wisconsin, Madison', email: 'gekeene@wisc.edu', office: '1202 W Johnson St, Madison, WI 53706', image: 'assets/img/contact.jpg'}
